name: Auto Restart VPS

on:
  schedule:
    - cron: "0 */6 * * *"  # otomatis tiap 6 jam
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger VPS Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/vps.yml/dispatches \
            -d '{"ref":"main"}'
